export const ERRORS = {
  INVALID_TRANSITION: "INVALID_TRANSITION",
  OVERLAP_CONFLICT: "OVERLAP_CONFLICT",
  ENTITLEMENT_LOCKED: "ENTITLEMENT_LOCKED",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const

export type ErrorCode = (typeof ERRORS)[keyof typeof ERRORS]
